feat: Add powermenu plugin
anyrun-org/anyrun pull request #203
Opened 2024-12-18 19:19 UTC by bcyran

A simple plugin I find very helpful and use everyday. Here's an example of how it looks in action:

![2024-12-18_20:08:56](https://github.com/user-attachments/assets/1ff6afdf-bafc-408a-a8ac-7da36e0cbc9e)
![2024-12-18_20:10:14](https://github.com/user-attachments/assets/cce92e25-818c-47bc-80b4-dcb1fbb38183)

I get that anyrun is in maintenance mode - I leave it to the maintainers to decide whether this should or should not be merged.

2025-10-20 16:01 UTC, bcyran commented
Hi @Kirottu, now that you're back, may I ask you for some feedback on this? Is this plugin of any interest to you? I just want to know whether it make sense for me to update the PR.

2026-01-19 20:08 UTC, Kirottu commented
Sorry for the late reply, a rebase is needed for me to have a look at this. Though I do think having a powermenu plugin as a part of the core plugins would probably be a good idea.

2026-01-20 18:25 UTC, bcyran commented
No worries, thanks for the answer. I rebased and updated the PR.

2026-01-21 09:59 UTC, Kirottu requested changes
Alrighty, sorry again for the long delay but here's my review of it. I proposed some architectural refactors to make the plugin more extensible by end users and more maintainable if actions need to change for whatever reason. Also traditional code style bikeshedding, as is customary.

2026-01-21 09:59 UTC, Kirottu commented on plugins/powermenu/src/lib.rs
> +    let action_result = execute_power_action(power_action_config);
This should be implemented in `PowerActionConfig`/`PowerAction` as per earlier comment.

2026-01-21 09:59 UTC, Kirottu commented on plugins/powermenu/src/lib.rs
> +    } else if let Some(ref error_message) = state.error_message {
Minor nitpick, I prefer using `let Some(error_message) = &state.error_message` instead of using the `ref` keyword.

2026-01-21 09:59 UTC, Kirottu commented on plugins/powermenu/src/config.rs
> +impl Config {
For the default power actions, there should probably be a list of possible commands to run to accomodate different init systems. Or init agnostic power management commands (if applicable) could be used.

2026-01-21 09:59 UTC, Kirottu commented on plugins/powermenu/src/lib.rs
> +fn get_error_matches(error_message: &str) -> Vec<Match> {
Not sure how necessary error handling in a graphical way is for the plugin, I think outputting errors in stderr with `eprintln!` would be sufficient.

2026-01-21 09:59 UTC, Kirottu commented on plugins/powermenu/src/actions.rs
> +pub enum PowerAction {
Power actions could probably be represented as a configurable list instead of a hardcoded enum, so that adding new actions and/or removing unnecessary ones is easily configurable and extensible. So in effect `PowerAction` and `PowerActionConfig` could be merged into something like this:
```rust
struct PowerAction {
    title: String,
    desc: String,
    icon: String,
    // List of commands to try to perform the action, to accomodate other inits
    command: Vec<String>,
    confirm: bool,
}
```
The default config should of course contain all of the power options that are currently available in the code.

2026-01-21 09:59 UTC, Kirottu commented on plugins/powermenu/src/actions.rs
> +        matches_with_scores.sort_by_key(|(_action, score)| *score);
The sorting seems to be inverted, since poweroff/shutdown is the last one with this query:
<img width="804" height="363" alt="image" src="https://github.com/user-attachments/assets/a93fe308-f79f-4422-9c87-a3cf8c9a13b2" />

2026-01-21 09:59 UTC, Kirottu commented on plugins/powermenu/Cargo.toml
> +version = "0.1.0"
Version should be the same as the other versions in the repo right now, so `25.12.0`.

2026-01-21 16:22 UTC, bcyran commented on plugins/powermenu/src/actions.rs
> +pub enum PowerAction {
I actually intended to implement a generic "command runner" plugin some day. I feel like after applying this suggestion, this plugin would be pretty much just that, but with power management commands included by default.

So, maybe we could drop the `powermenu` plugin and make more generic `commandrunner`. Power management actions could be then either:
* just an example config in the readme, or,
* embedded in the plugin and enabled using some predefined option.

What do you think?

2026-01-21 18:20 UTC, Kirottu commented on plugins/powermenu/src/actions.rs
> +pub enum PowerAction {
Yea that would basically turn this into a generic command runner, so I think `actions` is a better name to describe what it does. I do think power management actions are a good default to have in the default config and thus should also be in the README to hopefully reduce any possible confusion (and also to provide easy examples).

2026-02-19 19:31 UTC, bcyran commented on plugins/powermenu/src/lib.rs
> +    let action_result = execute_power_action(power_action_config);
Absolutely, done.

2026-02-19 19:31 UTC, bcyran commented on plugins/powermenu/src/lib.rs
> +    } else if let Some(ref error_message) = state.error_message {
Sure, done.

2026-02-19 19:32 UTC, bcyran commented on plugins/powermenu/src/actions.rs
> +        matches_with_scores.sort_by_key(|(_action, score)| *score);
No idea how I didn't notice this while using this for over a year. Fixed.

2026-02-19 19:32 UTC, bcyran commented on plugins/powermenu/Cargo.toml
> +version = "0.1.0"
Corrected.

2026-02-19 19:34 UTC, bcyran commented on plugins/powermenu/src/lib.rs
> +fn get_error_matches(error_message: &str) -> Vec<Match> {
I strongly disagree with this. GUI application needs a GUI way to communicate errors. Just failing silently in GUI and outputting logs somewhere is terrible UX IMHO.

Of course you're the boss here so let me know if you won't accept this. But I personally think it is necessary.

2026-02-19 19:47 UTC, bcyran commented on plugins/powermenu/src/config.rs
> +impl Config {
I'm not convinced dedicated support for this is necessary. Since the commands are passed through shell it's possible to fallback using `||`. I guess I don't have a strong opinion here but I think it would be a bit unexpected to provide a list of commands in the user config - you don't usually see this when configuring keybinds for example. If we want that only for default commands and not for the user config then we would need to somehow separate those two in the code which is ok but I'm not sure if it's worth the trouble when other solution exists.

2026-02-19 19:48 UTC, bcyran commented on plugins/powermenu/src/actions.rs
> +pub enum PowerAction {
I renamed the plugin to "Actions" and rewritten most of it. It's completely generic now.

For now it doesn't include any actions by default - power management actions are presented in the example config. The reason is that I don't have a good idea how to provide the power actions by default while allowing the user to:
- edit the default actions,
- opt out of some or all of the default actions,
- add their own custom actions.

I think the best idea I have is something like `power_management_actions: bool` in the config. It would be enabled by default and you could disable it by setting to `false`. No way to modify the actions - either you take the default config or you reject it.

This is something I definitely need your input on.

2026-02-19 19:50 UTC, bcyran commented
@Kirottu Sorry for the delay. I think this is ready for another round of review when you find some time.

2026-02-22 09:48 UTC, Kirottu reviewed
A few things need a bit of tweaking, after that I'll do some functionality testing of it.

2026-02-22 09:48 UTC, Kirottu commented on plugins/actions/src/lib.rs
> +    description: String,
Description can probably also be annotated with `#[serde(default)]`

2026-02-22 09:48 UTC, Kirottu commented on plugins/actions/src/lib.rs
> +        |content| ron::from_str(&content).unwrap_or_default(),
Should output an error log if parsing fails, otherwise users will have no clue what part of the process failed. The default config should still be used though.

2026-02-22 09:48 UTC, Kirottu commented on plugins/actions/README.md
> +No actions are configured by default. You need to add them to the configuration file.
I think it would make sense to have power actions be the default config, since that is likely a common use case for this plugin. They should also preferably have as init agnostic commands for the actions as possible.

2026-02-24 09:04 UTC, bcyran commented on plugins/actions/src/lib.rs
> +    description: String,
Sure, done.

2026-02-24 09:04 UTC, bcyran commented on plugins/actions/src/lib.rs
> +        |content| ron::from_str(&content).unwrap_or_default(),
Absolutely, thanks for pointing this out. Added.

2026-02-24 09:07 UTC, bcyran commented on plugins/actions/README.md
> +No actions are configured by default. You need to add them to the configuration file.
The power actions are active by default now. One can disable them by setting `enable_power_actions` to `false` in the config. I also added non-systemd fallback commands where I knew them.

2026-02-24 09:13 UTC, bcyran commented
@Kirottu Thanks for the review. All comments addressed, I think this is more or less ready now.

2026-03-04 21:16 UTC, Kirottu reviewed
Only a small nitpick left, after that this can be merged.

2026-03-04 21:16 UTC, Kirottu commented on plugins/actions/src/lib.rs
> +            .max(matcher.fuzzy_match(&self.description, phrase))
The description should be weighted less, something like

```rust
        matcher.fuzzy_match(&self.title, phrase).max(
            matcher
                .fuzzy_match(&self.description, phrase)
                .map(|x| x / 2),
        )
```

should do. Otherwise, starting to type out "Suspend" would result with Hibernate as the higher result, which is suboptimal.

2026-03-05 19:03 UTC, bcyran commented on plugins/actions/src/lib.rs
> +            .max(matcher.fuzzy_match(&self.description, phrase))
Right, that makes sense! Applied.

2026-03-09 14:48 UTC, Kirottu approved these changes
LGTM!

2026-03-09 14:50 UTC, merged